### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by omerts** [maitria/mock-api-server#12]
Hello,

Installing on 64bit windows machine, I get the following error:

```
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  curllib.cc
..\curllib.cc(11): fatal error C1083: Cannot open include file: 'curl/curl.h': No such file or directory [c:\fe\node_modules\mock-api-server\node_modules\http-sync\build\curllib.vcxproj]
```

**Comment by Kresshy** [comment]
We also have the same problem during the installation. http-sync-4 module cannot find the curllib.cc

**Comment by eraserhd** [comment]
@omerts @Kresshy I just merged a PR from @claudiamatosa that uses a different module that does not depend on curllib, so this should now work.
